[tool.poetry]
name = "database"
version = "0.1.0"
description = ""
authors = ["Admin <admin@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
alembic = "^1.12.1"
sqlmodel = "^0.0.21"
pydantic-settings = "^2.12.0"
pgvector = "^0.2.5"

#TODO: Remove strawberry-graphql from here when we migrate schemas or transition legacy.
strawberry-graphql = { extras = ["fastapi"], version = "^0.262.6" }
psycopg2-binary = "^2.9.9"
asyncpg = "^0.29.0"
sqlalchemy-utils = "^0.41.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
mypy = "^1.8.0"
pre-commit = "^3.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
