name: Backend Dev Deployment
on:
  workflow_run:
    workflows: ["Unit Test"]
    branches: ["develop"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' && github.event_name == 'workflow_run')
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v6
      - name: Trigger deployment repo workflow
        run: |
          set -e

          # Make the request and capture HTTP status code
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEP_REPO_WORKFLOW_DISPATH_TOKEN }}" \
            https://api.github.com/repos/driver-ai/deployment/actions/workflows/develop.yaml/dispatches \
            -d '{"ref":"develop"}')

          echo "HTTP status: $STATUS"

          # Expect 204 No Content
          if [ "$STATUS" -ne 204 ]; then
            echo "❌ Failed to trigger workflow. Expected 204 but got $STATUS"
            exit 1
          fi

          echo "✅ Successfully triggered workflow."
