name: Backend Ops Deployment
on:
  push:
    branches: ["ops"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
jobs:
  ops:
    # needs: unittest
    runs-on: ubuntu-latest
    environment: ops
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies without virtualenv
        run: poetry install --no-root
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_CICD_ROLE }}
      - name: CDK Deploy
        env:
          DEPLOYMENT_ENVIRONMENT: ops
        run: poetry run npx cdk deploy --require-approval never
      # Uses the dev environment Modal currently, probably not worth it to configure new modal environments for this env yet
